Feature/home work 2
XJIEBYUJEK/Intensiv pull request #2
Opened 2024-08-08 00:43 UTC by XJIEBYUJEK

2024-08-08 22:39 UTC, AndroidStudentClub requested changes
Проверил

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
Версии библиотек желательно выносить в константы. Это делается для того, чтобы не было ошибок которые возникают при разных версиях библиотек. 

Желательно вынести все версии библиотек тоже в константы как в проекте выше. Пример $rootProject.timberVersion"

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +    private const val BASE_URL = "https://api.themoviedb.org/3/"
buildConfigField 'String', 'BASE_URL', '"https://api.themoviedb.org/3/"'. В целом, хорошей практикой является вынесение базового урл в build.gradle

Это может пригодится, когда у нас разные урл (например один для тестового билда/второй для настоящего который в проде)

Вот статья на эту тему https://medium.com/@ramonrabello/best-practices-for-working-with-different-build-types-c5cd08b1adc6Смотреть пункт [#3](https://github.com/dfyz8-g/MoviesApp/pull/3) Way: Using Gradle Build Config Fields

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/TvShow.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Тут везде дублируется image URL. Если он поменяется - то придется менять по всему проекту, где-то забудется и будет баг. Поэтому лучше imageUrl тоже вынести например также как основной URL, чтобы поменять было легко.

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/TvShow.kt
> +        get() = voteAverage?.div(2)?.toFloat()
Magic Number

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiClient.kt
> +        .addInterceptor(HttpLoggingInterceptor().apply {
Да, все верно, единственное нужно учесть что в текущей реализации даже если приложение будет собрано для релиза в прод - то там тоже будут логи видны, а это плохо. Можно добавить проверку типа
Build.Config!=Release - чтобы в релизной сборке не было видно логов

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                Picasso.get()
Код для загрузки картики повторяется - можно сделать проще, написав один раз extension для ImageView внутри которого будет эта логика. В итоге будет что-то типа imagePreview.loadImage(url)

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                binding.actor1Text.text = actors?.get(0)?.name ?: ""
Тут лучше использовать RecyclerView. Это будет более гибкое решение, будет работать как для 4 актеров так и для 400. C Recycler-ом можно тоже через Groupie сделать как на экране сериалов.

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                binding.actor2Text.text = actors?.get(1)?.name ?: ""
Захкардкоженные индексы лучше не использовать. Что если будет фильм где будет всего 1 актер? Тут тогда будет IndexOutOfBoundsException. Поэтому лучше делать эту часть через RecyclerView - такое решение не масштабируется, заивисит от ответа сервера и требует постоянной поддержки

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                Picasso.get()
Ну и если сделать через Recycler - это тоже не придется повторять. Кстати не обязательно если используем Recycler то должно быть 100500+ элементов. Как видно из этого примера использовать ресайклер даже для небольшого кол-ва данных будет проще в поддержке и масштабировании

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +                    .load(actors?.get(2)?.profilePath)
Если кол-во актеров изменится - получим Exception

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        _binding = null
Вот эта часть с ViewBinding будет часто повторятся. Тут можно создать базовый класс в котором будет инкапсулирована эта логика и потом переиспользована. Например:

```
abstract class BaseFragment<Binding : ViewBinding> : Fragment() {

    protected val binding: Binding get() = _binding!!
    private var _binding: Binding? = null

    abstract fun createViewBinding(inflater: LayoutInflater, container: ViewGroup?): Binding

    final override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = createViewBinding(inflater, container)
        return binding.root
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
```

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowItem.kt
>          Picasso.get()
Вот этот код повторяется - можно сделать проще, написав один раз extension для ImageView внутри которого будет эта логика. В итоге будет что-то типа imagePreview.loadImage(url)

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/tvshows/TvShowsFragment.kt
> +        val getPopularTvShows = MovieApiClient.apiClient.getPopularTvShows(API_KEY, "en-US")
У тебя уже была константа ENGLISH можно ее переиспользовать. А вообще эти аргументы можно перенсти в дефолтные аргументы при описании API в интерфейсе для ретрофита, так как они везде будут одинаковые

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:id="@+id/actor4_image"
Не, список актеров нужно делать через RecyclerView - так будет правильней

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:id="@+id/actor4_text"
Смотри это верстка для 4 актеров - а если их будет 10? Нужно использовать RecyclerView

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_header.xml
> +                android:layout_height="400dp"
Размеры, цвета, строки рекомендуется выносить в ресурсы

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/res/layout/movie_details_fragment.xml
> +                android:id="@+id/movie_title"
Не увидел в этом макете UI компонента для лайка для добавления фильма в избранное - нам это попозже понадобится

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/watchlist/MoviePreviewItem.kt
> +    private val content: Movie_temp,
Нэйминг лучше не смешивать, или CamelCase или lower_snake_case

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +    fun getNowPlaying(@Query("api_key") apiKey: String, @Query("language") language: String): Call<MoviesResponse>
В этих методах имел ввиду использовать дефолтные аргументы

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDetails.kt
> +        get() = "https://image.tmdb.org/t/p/w500$field"
Тут еще вот какой момент о котором стоит подумать. Параметр w500 - тут получается является частью  урла - а если надо поменять размер картинки - то в таком случае это будет сделать невозможно. Так что w500 можно теоретически вынести отсюда/заменить константой чтобы быстро поменять/сделать утилитный метод которые будет создавать урл для картинки из входящих параметров.

2024-08-08 22:39 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDetails.kt
> +        get() = voteAverage?.div(2)?.toFloat()
Вот этот код дублируется много где, если понадобится изменить логику подсчета рейтинга придется искать все места/обновлять множество моделей.

2024-08-13 14:59 UTC, XJIEBYUJEK commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
> +        _binding = null
Не смог разобраться как его правильно в дальнейшем наследовать

2024-08-13 18:47 UTC, XJIEBYUJEK commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDetails.kt
> +        get() = voteAverage?.div(2)?.toFloat()
То есть функцию подсчета рейтинга реализовать в какой-нибудь extension и потом просто вызывать во всех классах?

2024-08-13 19:00 UTC, XJIEBYUJEK commented
В последнем коммите я добавил наследство ProfileFragment  чтобы просто показать как я это понял, и вот в его случае вроде все ок работает. Но у меня нет идеи что делать когда у нас есть еще другой binding например в SearchFragment есть searchBinding, который мы биндим в onCreate, но после наследства мы ее больше не можем вызывать. Поэтому вот можешь показать пример наследства от BaseFragment на SearchFragment как раз, пока в нем мало логики.

2024-08-13 23:07 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/data/MovieDetails.kt
> +        get() = voteAverage?.div(2)?.toFloat()
Да, можно так

2024-08-13 23:08 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +    fun getMovieDetails(@Path("id") id: Int, @Query("api_key") apiKey: String, @Query("language") language: String = "en-US"): Call<MovieDetails>
"en-US" - в константу либо еще можно через метод Locale.getDefault().toLanguageTag()

2024-08-13 23:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/network/MovieApiInterface.kt
> +    fun getMovieCredits(@Path("id") id: Int, @Query("api_key") apiKey: String, @Query("language") language: String = "en-US"): Call<CreditsResponse>
"en-US" - в константу либо еще можно через метод Locale.getDefault().toLanguageTag()
Любой код/значение если дублируется, то необходимо его куда то выносить

2024-08-13 23:10 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/CastItem.kt
> +        Picasso.get()
Вот этот код повторяется - можно сделать проще, написав один раз extension для ImageView внутри которого будет эта логика. В итоге будет что-то типа imagePreview.loadImage(url)

2024-08-13 23:15 UTC, AndroidStudentClub commented
> В последнем коммите я добавил наследство ProfileFragment чтобы просто показать как я это понял, и вот в его случае вроде все ок работает. Но у меня нет идеи что делать когда у нас есть еще другой binding например в SearchFragment есть searchBinding, который мы биндим в onCreate, но после наследства мы ее больше не можем вызывать. Поэтому вот можешь показать пример наследства от BaseFragment на SearchFragment как раз, пока в нем мало логики.

Так, а будет точно также. Нужно будет наследоваться от BaseFragment и переопределить метод    abstract fun createViewBinding(inflater: LayoutInflater, container: ViewGroup?): Binding в дочернем фрагменте. Таким образом в родительском фрагементе когда вызовется 

```
 final override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = createViewBinding(inflater, container) // Вот его переопределили и получили биндинг для searchFragment
        return binding.root
    }
```

2024-08-15 12:22 UTC, XJIEBYUJEK commented
Залил коммит с ошибкой, а то я так и не разобрался...

2024-08-15 19:17 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
Тут нужно добавить  биндинг основной   private var _movieDetailsBinding: MovieDetailsFragmentBinding? = null

2024-08-15 19:17 UTC, AndroidStudentClub commented on app/src/main/java/ru/androidschool/intensiv/ui/movie_details/MovieDetailsFragment.kt
>          _posterBinding = MovieDetailsHeaderBinding.bind(binding.root)
Тут надо будет передать root того биндинга в который мы инклюдим posterHeader, то есть должно быть вот так:
```

 override fun createViewBinding(
        inflater: LayoutInflater,
        container: ViewGroup?
    ): MovieDetailsFragmentBinding {
        _movieDetailsBinding = MovieDetailsFragmentBinding.inflate(inflater, container, false)
        _posterBinding = MovieDetailsHeaderBinding.bind(_movieDetailsBinding!!.root)
        return _movieDetailsBinding!!
    }

```

2024-08-15 20:09 UTC, closed without merging